### ISSUE TITLE
Create, Delete resolve

### ISSUE THREAD

**Issue by cbaja** [cbaja/MyTodoList#3]
I got the way to fix the way to Create , Delete records on the database.
/cc @codepathreview and @codepath

**Comment by nesquena** [comment]
Great to see you were able to augment your app with a few extension tasks now. As mentioned earlier, the extension tasks available on each project are often the most valuable learnings since they dive deeper into common real-world Android use cases.

After reviewing your project, I'd encourage you to take a look at [this guide on code organization best practices](http://guides.codepath.com/android/Organizing-your-Source-Files) to cleanup your source code. Will be reaching out over email soon.

**Comment by cbaja** [comment]
Thanks Nesquena,
I am going to take a look on the guide and make some cleanup on my source code. 
and I am steel working in the project.
/cc @codepathreview and @codepath
